# Generated by Django 4.1.13 on 2025-06-07 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('portada', models.ImageField(upload_to='portadas/')),
                ('portada_grande', models.ImageField(upload_to='portadas_grandes/')),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_akeno.anime')),
            ],
        ),
        migrations.CreateModel(
            name='Episodio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('portada_ep', models.ImageField(blank=True, null=True, upload_to='portadas_episodios/')),
                ('temporada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_akeno.temporada')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='etiquetas',
            field=models.ManyToManyField(to='app_akeno.etiqueta'),
        ),
    ]
